host:   0.0.0.0
port:   4000
url: http://localhost:4000
permalink: /:year/:title
paginate: 6
destination: _site
future: false
show_drafts: nil
markdown: rdiscount
safe: true
lsi: false
pygments: true
sass:
    syntax: scss        # scss|sass
    style:  compressed  # nested|expanded|compact|compressed
