host:   0.0.0.0
port:   4000
url: http://localhost:4000
permalink: /:year/:title
exclude: [node_modules, bower_components]
paginate: 6
destination: _site
future: false
show_drafts: nil
markdown: rdiscount
safe: true
lsi: false
pygments: true
gems:
  - jekyll-sitemap
